In [1]:
import numpy as np

# Set a fixed seed to ensure reproducibility
np.random.seed(10)
matrix_with_seed = np.random.randint(1, 51, size=(3, 3))
print(matrix_with_seed)


[[10 37 16]
 [ 1 50 29]
 [26 30 49]]


In [2]:
import numpy as np

# No fixed seed, random numbers will change every time
np.random.seed(None)
matrix_without_seed = np.random.randint(1, 51, size=(3, 3))
print(matrix_without_seed)


[[37 46 30]
 [45 26 11]
 [26 38 44]]
